# Generated by Django 5.2.2 on 2025-06-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='dynamic_ring_loss_threshold',
            field=models.IntegerField(default=5000000, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='rollup_context_id',
            field=models.IntegerField(default=42, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
